import os
import time
from dotenv import load_dotenv

# Load env variables before importing
load_dotenv()

from genome.genome import MemoryGenome
from genome.vector_store import clear_all_memories, get_qdrant_client
from agent.graph import agent_app

def run_agent_conversation(genome: MemoryGenome, genome_name: str):
    print("\n" + "=" * 80)
    print(f"RUNNING CONVERSATION WITH: {genome_name}")
    print(f"Genome Config: {genome.to_dict()}")
    print("=" * 80)
    
    # Clean the memories for a fresh agent instance
    clear_all_memories()
    
    # State initialization
    state = {
        "messages": [],
        "current_input": "",
        "retrieved_memories": [],
        "response": "",
        "step": 0,
        "genome": genome,
        "agent_logs": []
    }
    
    # 6-turn dialogue
    turns = [
        "Hi! My name is Alice, my favorite programming language is Rust, and my dog's name is Rusty.",
        "Can you explain what a Large Language Model is in one sentence?",
        "What are the main advantages of compiling code vs interpreting it?",
        "Tell me a short joke about programming.",
        "What is your name and how does your memory work?",
        "Do you remember my name? Also, what is my favorite programming language and my dog's name?"
    ]
    
    for turn_idx, user_input in enumerate(turns):
        print(f"\n[Turn {turn_idx + 1}] User: {user_input}")
        if turn_idx == len(turns) - 1:
            print("  [System] Clearing short-term context history to force reliance on RAG retrieval...")
            state["messages"] = []
        state["current_input"] = user_input
        
        # Invoke LangGraph app
        output = agent_app.invoke(state)
        
        # Update conversation history in state
        state["messages"].append({"role": "user", "content": user_input})
        state["messages"].append({"role": "assistant", "content": output["response"]})
        state["step"] = output["step"]
        state["agent_logs"] = output["agent_logs"]
        
        print(f"Agent: {output['response']}")
        
        # Print logs generated by the nodes (optional: print only interesting ones like consolidation)
        for log in output["agent_logs"]:
            if "Consolidation Checkpoint" in log or "Forgetting:" in log or "Compression:" in log or "Capacity:" in log:
                print(f"  >>> LOG: {log}")
                
        # Clear log buffer for next turn
        state["agent_logs"] = []
        
        # Small sleep to ensure timestamps differ slightly
        time.sleep(0.5)
        
    return output["response"]

def main():
    print("GenomeRAG - Multi-Turn Agent Memory Test")
    print("=========================================")
    
    # Sensible genome: standard retrieval, low forgetting, consolidation every 5 steps
    sensible_genome = MemoryGenome(
        forgetting_rate=0.0,
        retrieval_top_k=5,
        consolidation_freq=5,
        compression_ratio=0.5,
        memory_capacity=50,
        similarity_threshold=0.2
    )
    
    # Forgetful genome: high forgetting rate (0.99), consolidation every 3 steps
    forgetful_genome = MemoryGenome(
        forgetting_rate=0.99,
        retrieval_top_k=5,
        consolidation_freq=3,
        compression_ratio=0.5,
        memory_capacity=50,
        similarity_threshold=0.2
    )
    
    # Run Sensible Agent
    sensible_reply = run_agent_conversation(sensible_genome, "SENSIBLE AGENT")
    
    # Run Forgetful Agent
    forgetful_reply = run_agent_conversation(forgetful_genome, "FORGETFUL AGENT")
    
    print("\n" + "=" * 80)
    print("FINAL COMPARISON ON TURN 6:")
    print("=" * 80)
    print(f"Sensible Agent Reply:   {sensible_reply}")
    print(f"Forgetful Agent Reply:  {forgetful_reply}")
    print("=" * 80)

if __name__ == "__main__":
    main()
